language: python
python:
  - 2.7_with_system_site_packages
  - '3.2'
  - pypy
cache:
  directories:
    - $HOME/.cache/pip
sudo: false
matrix:
  fast_finish: true
  allow_failures:
    - python: '3.2'
    - python: pypy
env:
  - INTEGRATION_TEST=1
  - UNIT_TEST=1
addons:
  apt:
    sources:
    - trusty-media
    packages:
    - libcurl4-openssl-dev
    - python-numpy
    - python-opencv
    - libimage-exiftool-perl
    - libopencv-dev
    - libjpeg-progs
    - libjpeg-dev
    - libpng-dev
    - libx264-dev
    - libass-dev
    - libvpx-dev
    - libwebp-dev
    - webp
    - gifsicle
    - python-numpy
    - python-scipy
    - cython
    - ffmpeg
install:
  - pip install --upgrade pip
  - make setup
  - pip install coveralls
before_script:
  - make redis
script:
  make compile_ext ci_test
notifications:
  slack:
    secure: Sf6TJa/H3mq+RGqpLwKNRpNw0YQKX3+5bt5e37CSs8rOC+SoFHVNr29QhbXFPwmqQuy9qKb0t5rzChDIIvXErywU2lEw3/JlQtCt1xLsoUfpBF8g8ldoy6ESO2j9Jj6Y/M/4RN2zN3AAd5gfXPrdLHa++eiRaiAXXU+9ZvtUxuc=
after_success:
  coveralls

